services:
  - type: web
    name: spring-crud
    env: docker
    rootDirectory: pdv
    dockerfilePath: Dockerfile
    buildCommand: docker build -t spring-crud .
    startCommand: docker run -p $PORT:8081 spring-crud
    envVars:
      - key: PORT
        value: 8081
      - key: SPRING_DATASOURCE_URL
        value: jdbc:sqlserver://spring_db.mssql.somee.com:1433;databaseName=spring_db;encrypt=true;trustServerCertificate=true
      - key: SPRING_DATASOURCE_USERNAME
        value: Marcelzin_SQLLogin_1
      - key: SPRING_DATASOURCE_PASSWORD
        value: 35f6o9c1q2 